import { StyleSheet } from "react-native";
import { Colors } from "../../constants/colors";
import { Typography } from "../../constants/typo";
import { spacing } from "../../design-system/spacing";
import { textStyles } from "../../design-system/typography";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background.light, // White background
  },
  homeRoot: {
    flex: 1,
    backgroundColor: Colors.background.light,
    overflow: "visible",
  },
  homeBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  homeDecorativeContainer: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0.12,
  },
  homeDecorativeCircle: {
    position: "absolute",
    borderRadius: 999,
    backgroundColor: Colors.background.light,
  },
  homeCircle1: {
    width: 220,
    height: 220,
    top: -80,
    right: -60,
  },
  homeCircle2: {
    width: 150,
    height: 150,
    bottom: 180,
    left: -50,
  },
  homeCircle3: {
    width: 120,
    height: 120,
    top: "38%",
    right: 30,
  },
  headerBackground: {
    width: "100%",
    position: 'relative',
  },
  guestWelcomeWrap: {
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  guestWelcomeText: {
    color: Colors.background.light,
    fontSize: 18,
    fontFamily: Typography.fontFamily.bold,
    fontWeight: '700',
  },
  heroActionsOverlay: {
    position: 'absolute',
    top: 4,
    right: 4,
    flexDirection: 'row',
    gap: 2,
    zIndex: 5,
  },
  heroActionButton: {
    width: 30,
    height: 30,
    borderRadius: 999,
    backgroundColor: Colors.alpha.black50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.alpha.white40,
  },
  documentExpiryOverlay: {
    width: '100%',
    paddingHorizontal: 16,
    marginTop: 16,
  },
  garageSummaryWrap: {
    width: '100%',
    paddingHorizontal: 0,
    marginTop: 0,
    marginBottom: 10,
  },
  documentExpiryContainer: {
    backgroundColor: "transparent",
  },
  bannerInlineWrap: {
    width: '100%',
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 0,
  },
  bottomSheetContent: {
    paddingTop: spacing.lg,
  },
  bottomSheet: {
    flex: 1,
    width: '100%',
    backgroundColor: Colors.background.light,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 16,
    gap: 16,
    marginTop: 16,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
  },
  contentWrapper: {
    flex: 1,
    backgroundColor: Colors.background.light, // White background for content
  },
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
    gap: spacing.lg,
  },
  section: {
    gap: 16,
    width: '100%',
  },
  servicesContainer: {
    gap: 8,
    width: "100%",
  },
  loadingContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: spacing['3xl'],
  },
  loadingText: {
    marginTop: spacing.md,
    color: Colors.text.secondary,
    ...textStyles.body,
  },
  emptyContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: spacing['3xl'],
  },
  emptyText: {
    marginTop: spacing.md,
    color: Colors.text.secondary,
    ...textStyles.body,
  },
  loginPromptCard: {
    backgroundColor: Colors.background.light,
    borderRadius: 24,
    padding: spacing.xl,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.primary,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
    gap: spacing.md,
  },
  loginPromptTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  loginPromptDescription: {
    fontSize: 14,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.regular,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: spacing.sm,
  },
  loginPromptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: 16,
    gap: spacing.sm,
    marginTop: spacing.sm,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  loginPromptButtonText: {
    color: Colors.background.light,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: Typography.fontFamily.bold,
  },
  garageCard: {
    width: '100%',
    borderRadius: 22,
    backgroundColor: Colors.background.light,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
    gap: spacing.sm,
  },
  garageCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  garageCardIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  garageCardContent: {
    flex: 1,
    gap: 2,
  },
  garageCardTitle: {
    fontSize: 16,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
  },
  garageCardCode: {
    fontSize: 13,
    color: Colors.primaryLight,
    fontFamily: Typography.fontFamily.medium,
  },
  garageCardMeta: {
    fontSize: 13,
    lineHeight: 20,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.regular,
  },
  promoEmptyCard: {
    borderRadius: 22,
    backgroundColor: Colors.surface.muted,
    padding: spacing.xl,
    gap: spacing.sm,
  },
  promoEmptyTitle: {
    fontSize: 16,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
  },
  promoEmptyDescription: {
    fontSize: 14,
    lineHeight: 21,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.regular,
  },
  promoStepsCard: {
    borderRadius: 22,
    padding: spacing.xl,
    backgroundColor: Colors.secondarySoft,
    gap: spacing.sm,
  },
  noticeBanner: {
    borderRadius: 20,
    padding: spacing.md,
    backgroundColor: Colors.background.light,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: spacing.sm,
  },
  noticeBannerIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeBannerContent: {
    flex: 1,
    gap: 4,
  },
  noticeBannerTitle: {
    fontSize: 14,
    lineHeight: 20,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
  },
  noticeBannerText: {
    fontSize: 12,
    lineHeight: 18,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.regular,
  },
  noticeBannerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  noticeBannerClose: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: Colors.neutral[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  noticeBannerAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Colors.primarySoft,
  },
  noticeBannerActionText: {
    fontSize: 12,
    color: Colors.primary,
    fontFamily: Typography.fontFamily.bold,
  },
  promoStepText: {
    fontSize: 14,
    lineHeight: 22,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.medium,
  },
  // Employee Orders List
  employeeOrdersContainer: {
    width: '100%',
  },
  statusFilterContainer: {
    marginBottom: spacing.md,
  },
  statusFilterContent: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  statusFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 20,
    backgroundColor: Colors.neutral[100],
    borderWidth: 1,
    borderColor: Colors.neutral[300],
  },
  statusFilterButtonActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  statusFilterText: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.medium,
    color: Colors.text.secondary,
  },
  statusFilterTextActive: {
    color: Colors.background.light,
  },
  // Customers List
  customersContainer: {
    width: '100%',
  },
  customersContent: {
    gap: spacing.md,
  },
  customerCard: {
    width: '100%',
    backgroundColor: Colors.background.light,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: spacing.md,
  },
  customerCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  customerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  customerInfo: {
    flex: 1,
  },
  customerName: {
    fontSize: 15,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.text.primary,
    marginBottom: 2,
  },
  customerPhone: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.regular,
    color: Colors.text.secondary,
  },
  activeOrdersBadge: {
    backgroundColor: Colors.primary,
    borderRadius: 12,
    minWidth: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  activeOrdersBadgeText: {
    color: Colors.background.light,
    fontSize: 12,
    fontFamily: Typography.fontFamily.bold,
    fontWeight: 'bold',
  },
  customerStats: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.xs,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: Colors.neutral[200],
  },
  customerStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  customerStatText: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.regular,
    color: Colors.text.secondary,
  },
  // Warranty Info
  warrantyContainer: {
    width: '100%',
    gap: spacing.md,
  },
  warrantyCard: {
    backgroundColor: Colors.background.light,
    borderRadius: 16,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  warrantyCardExpired: {
    borderColor: Colors.status.error,
    backgroundColor: Colors.status.error + '10',
  },
  warrantyCardExpiring: {
    borderColor: Colors.status.warning,
    backgroundColor: Colors.status.warning + '10',
  },
  warrantyCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  warrantyIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  warrantyInfo: {
    flex: 1,
  },
  warrantyServiceName: {
    fontSize: 15,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.text.primary,
    marginBottom: 4,
  },
  warrantyCustomerName: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.regular,
    color: Colors.text.secondary,
    marginBottom: 2,
  },
  warrantyLicensePlate: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.regular,
    color: Colors.text.secondary,
  },
  warrantyBadge: {
    backgroundColor: Colors.status.error,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  warrantyBadgeWarning: {
    backgroundColor: Colors.status.warning,
  },
  warrantyBadgeText: {
    color: Colors.background.light,
    fontSize: 10,
    fontFamily: Typography.fontFamily.bold,
    fontWeight: 'bold',
  },
  warrantyDetails: {
    gap: spacing.xs,
  },
  warrantyDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  warrantyDetailText: {
    fontSize: 13,
    fontFamily: Typography.fontFamily.regular,
    color: Colors.text.secondary,
  },
  warrantyDetailTextExpired: {
    color: Colors.status.error,
  },
  warrantyNote: {
    marginTop: spacing.xs,
    padding: spacing.sm,
    backgroundColor: Colors.neutral[50],
    borderRadius: 8,
  },
  warrantyNoteText: {
    fontSize: 12,
    fontFamily: Typography.fontFamily.regular,
    color: Colors.text.secondary,
    fontStyle: 'italic',
  },
  managerKpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  managerKpiCard: {
    width: '48%',
    backgroundColor: Colors.background.light,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
    borderRadius: 14,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    gap: 4,
  },
  managerKpiValue: {
    fontSize: 22,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
  },
  managerKpiLabel: {
    fontSize: 12,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
  },
  managerActionsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  managerActionButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.primary,
    backgroundColor: Colors.primarySoft,
    borderRadius: 12,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  managerActionText: {
    fontSize: 12,
    color: Colors.primary,
    fontFamily: Typography.fontFamily.bold,
  },
});
