// src/screens/OrderDetail/styles.ts
import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';
import { Typography } from '../../constants/typo';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: Colors.background.light,
  },
  redSection: {
    backgroundColor: Colors.background.red,
    height: 80,
  },
  whiteSection: {
    flex: 1,
    backgroundColor: Colors.background.light,
  },
  body: {
    flex: 1,
    width: '100%',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 4,
  },
  scrollContent: {
    paddingBottom: 4,
  },
  billCard: {
    backgroundColor: Colors.background.light,
    borderRadius: 16,
    padding: 20,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: Colors.neutral[800],
    borderStyle: 'dashed',
    shadowColor: Colors.neutral[300],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
    paddingVertical: 4,
  },
  label: {
    fontSize: 14,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
    flex: 0.4,
    textAlign: 'left',
  },
  valueText: {
    fontSize: 14,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
    flex: 0.6,
    textAlign: 'right',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 4,
    backgroundColor: Colors.neutral[50],
    borderRadius: 8,
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  statusText: {
    fontSize: 12,
    color: Colors.text.white,
    fontWeight: 'bold',
    fontFamily: Typography.fontFamily.bold,
  },
  imageSection: {
    marginTop: 4,
    marginBottom: 4,
    minHeight: 120,
  },
  imageLabel: {
    fontSize: 14,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
    marginBottom: 4,
  },
  imageList: {
    paddingVertical: 4,
    alignItems: 'flex-start',
  },
  imageContainer: {
    alignItems: 'center',
    marginRight: 12,
    width: 100,
  },
  image: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  imageDesc: {
    fontSize: 10,
    color: Colors.text.secondary,
    textAlign: 'center',
    marginTop: 4,
    maxWidth: 100,
  },
  imageDate: {
    fontSize: 9,
    color: Colors.text.placeholder,
    textAlign: 'center',
    marginTop: 2,
    maxWidth: 100,
  },
  noImageText: {
    fontSize: 12,
    color: Colors.text.secondary,
    textAlign: 'center',
    marginTop: 4,
    fontFamily: Typography.fontFamily.regular,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.neutral[200],
    marginVertical: 4,
  },
  confirmationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    backgroundColor: Colors.neutral[50],
    borderRadius: 8,
  },
  confirmationText: {
    flex: 1,
    fontSize: 12,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.regular,
  },
  confirmationDate: {
    fontSize: 12,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
    marginRight: 8,
  },
  checkbox: {
    padding: 4,
  },
  warrantyCard: {
    marginBottom: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 4,
    gap: 8,
  },
  iconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.neutral[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
  },
  infoCard: {
    backgroundColor: Colors.background.light,
    borderRadius: 12,
    padding: 16,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: Colors.neutral[200],
    borderStyle: 'dashed',
    shadowColor: Colors.neutral[300],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  keyValueRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  key: {
    fontSize: 14,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
  },
  value: {
    fontSize: 14,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.regular,
    textAlign: 'right',
    flex: 1,
  },
  errorText: {
    textAlign: 'center',
    color: Colors.text.secondary,
    fontSize: 16,
    padding: 20,
  },
  // New styles for waiting confirmation button
  confirmButtonContainer: {
    marginTop: 4,
  },
  confirmButton: {
    backgroundColor: Colors.confirmbutton,
    borderRadius: 15,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: Colors.neutral[300],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  confirmButtonText: {
    color: Colors.text.white,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Typography.fontFamily.bold,
  },
  // New styles for completed warranty row
  warrantyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
    paddingVertical: 4,
  },
  warrantyLabel: {
    fontSize: 14,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
    flex: 0.4,
  },
  warrantyValue: {
    fontSize: 14,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.bold,
    flex: 0.6,
    textAlign: 'right',
  },
  warrantyCheckbox: {
    padding: 4,
    marginLeft: 8,
  },
  dashedDivider: {
    height: 1,
    borderStyle: 'dashed',
    borderTopWidth: 1,
    borderColor: Colors.neutral[300],
    marginVertical: 4,
  },
  warrantyEndRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    backgroundColor: Colors.neutral[50],
    borderRadius: 8,
    padding: 12,
  },
  warrantyEndLabel: {
    fontSize: 14,
    color: Colors.text.secondary,
    fontFamily: Typography.fontFamily.medium,
    flex: 1,
  },
  warrantyEndDate: {
    fontSize: 14,
    color: Colors.background.green,
    fontFamily: Typography.fontFamily.bold,
    textAlign: 'right',
  },
  // Modal styles for full screen image
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    padding: 10,
  },
  fullScreenImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  // Upload button styles
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.neutral[100],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  uploadButtonDisabled: {
    opacity: 0.5,
  },
  uploadButtonText: {
    fontSize: 12,
    color: Colors.text.primary,
    fontFamily: Typography.fontFamily.medium,
  },
});