import { StyleSheet } from "react-native";
import { Colors } from "../../constants/colors";
import { Typography } from "../../constants/typo";
import { spacing } from "../../design-system/spacing";
import { textStyles } from "../../design-system/typography";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background.muted,
  },
  scrollContent: {
    paddingBottom: spacing["2xl"],
  },
  heroContainer: {
    height: 292,
  },
  heroSurface: {
    flex: 1,
    paddingTop: spacing.xl,
    backgroundColor: Colors.primary,
  },
  heroDecorativeContainer: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0.12,
  },
  heroDecorativeCircle: {
    position: "absolute",
    borderRadius: 999,
    backgroundColor: Colors.background.light,
  },
  heroCircle1: {
    width: 220,
    height: 220,
    top: -80,
    right: -60,
  },
  heroCircle2: {
    width: 150,
    height: 150,
    bottom: 140,
    left: -50,
  },
  heroCircle3: {
    width: 120,
    height: 120,
    top: "34%",
    right: 30,
  },
  heroContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing["2xl"],
    gap: spacing.lg,
    zIndex: 1,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarShell: {
    width: 98,
    height: 98,
    borderRadius: 32,
    padding: 4,
    backgroundColor: Colors.alpha.white12,
    borderWidth: 1,
    borderColor: Colors.alpha.white20,
    marginRight: spacing.lg,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  avatar: {
    width: "100%",
    height: "100%",
    borderRadius: 28,
    backgroundColor: Colors.alpha.white12,
  },
  heroText: {
    flex: 1,
    gap: 4,
  },
  userName: {
    fontSize: 30,
    lineHeight: 34,
    fontFamily: Typography.fontFamily.semibold,
    fontWeight: Typography.weight.semibold,
    letterSpacing: -0.4,
    color: Colors.background.light,
  },
  userPhone: {
    ...textStyles.body,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.weight.medium,
    color: Colors.background.light,
  },
  roleChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: spacing.xs,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: Colors.secondaryLight,
    borderWidth: 1,
    borderColor: Colors.secondary,
  },
  roleChipText: {
    ...textStyles.bodySmall,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.weight.medium,
    letterSpacing: 0.2,
    color: Colors.background.light,
  },
  sheet: {
    marginTop: -64,
    backgroundColor: Colors.background.light,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    minHeight: 420,
  },
  sheetContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing["2xl"],
    gap: spacing.md,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
    minHeight: 68,
    borderWidth: 1,
    borderColor: Colors.alpha.primary12,
    borderRadius: 20,
    backgroundColor: Colors.surface.elevated,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  rowSpacing: {
    marginBottom: spacing.md,
  },
  rowPressed: {
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.alpha.primary20,
  },
  rowIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.md,
    borderWidth: 1,
    borderColor: Colors.alpha.primary12,
    backgroundColor: Colors.primarySoft,
  },
  rowText: {
    flex: 1,
    marginRight: spacing.md,
  },
  rowTitle: {
    ...textStyles.bodyStrong,
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.weight.medium,
    color: Colors.text.primary,
  },
  rowArrowWrap: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.alpha.primary08,
    borderWidth: 1,
    borderColor: Colors.alpha.primary12,
  },
  actionsGroup: {
    paddingTop: spacing.md,
    gap: spacing.md,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    minHeight: 58,
    borderWidth: 1,
    shadowColor: Colors.shadow.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  actionButtonPressed: {
    opacity: 0.92,
  },
  actionButtonDisabled: {
    opacity: 0.6,
  },
  actionIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md,
  },
  deleteButton: {
    backgroundColor: Colors.secondaryLight,
    borderColor: Colors.secondary,
  },
  deleteIconWrap: {
    backgroundColor: Colors.alpha.white18,
  },
  deleteButtonText: {
    ...textStyles.bodyStrong,
    fontFamily: Typography.fontFamily.semibold,
    fontWeight: Typography.weight.semibold,
    color: Colors.background.light,
  },
  logoutButton: {
    backgroundColor: Colors.surface.elevated,
    borderColor: Colors.primary,
  },
  logoutIconWrap: {
    backgroundColor: Colors.primarySoft,
  },
  logoutButtonText: {
    ...textStyles.bodyStrong,
    fontFamily: Typography.fontFamily.semibold,
    fontWeight: Typography.weight.semibold,
    color: Colors.primary,
  },
});
